config/routes.rb
Rails.application.routes.draw do

  resources :checks
  resources :accounts
  resources :deposits
  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :checks, dependent: :destroy
  has_many :deposits, dependent: :destroy
  validates :name, :balance, presence: true
  validates :balance, numericality: true
  
  def total_expense
    all_checks = checks.pluck(:amount)
    all_checks.sum
  end
  
  def total_deposits
    all_deposits = deposits.pluck(:amount)
    all_deposits.sum
  end
  
  def ending_balance
    balance - self.total_expense + self.total_deposits
    
  end
end

app/models/check.rb
class Check < ActiveRecord::Base
  validates :date, :to, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0.01 }
  validates :to, format: {without: /[<>{}\[\]]/}
  belongs_to :account
  
  
  
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  validates :date, :from, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0.01 }
  validates :from, format: {without: /[<>{}\[\]]/}
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def new 
    @account = Account.new
  end
  
  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:success] = "New account created"
      redirect_to accounts_url
    else
      flash[:danger] = "There were errors in your entry"
      render "new"
    end
  end
      
  def index
    @accounts = Account.all
  end
  
  def show
    @account = Account.find(params[:id])
  end
  
  def destroy
    Account.find(params[:id]).destroy
    flash[:success] = "Account deleted"
    redirect_to accounts_url
  end
  
  def edit
    @account = Account.find(params[:id])
  end
  
  private
  
    def account_params
      params.require(:account).permit(:name, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
    
  def new
    @account_options = Account.all.map{ |a| [a.name, a.id ] }
    @check = Check.new
  end
  
  def create
    @check = Check.new(check_params)
    if @check.save
      flash[:success] = "check saved"
      redirect_to new_check_url
    else
      flash[:danger] = "There are errors in your check"
      redirect_to new_check_url
    end
  end
  
  def show
    @check = Check.find(params[:id])
    @account = Account.where(id: @check.account_id)
  end
  
  def index
    @checks = Check.all
  end
  
  def destroy
    Check.find(params[:id]).destroy
    flash[:success] = "Check deleted"
    redirect_to accounts_url
  end
  
  private
  
    def check_params
      params.require(:check).permit(:date, :amount, :to, :account_id)
    end
  
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def new 
    @account_options = Account.all.map{ |a| [a.name, a.id ] }
    @deposit = Deposit.new
  end 

  def create
    @deposit = Deposit.new(deposit_params)
    if @deposit.save
      flash[:success] = "deposit saved"
      redirect_to new_deposit_url
    else
      flash[:danger] = "There were errors in your entry"
      redirect_to new_deposit_url
    end
  end


  def show
  end 
  
  def destroy
    Deposit.find(params[:id]).destroy
    flash[:success] = "Check deleted"
    redirect_to accounts_url
  end

  private
  
  def deposit_params
    params.require(:deposit).permit(:from, :amount, :date, :account_id)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/views/accounts/_checks.html.erb
<table>

  <tr>
    <th>Date</th>
    <th>Paid to</th>
    <th>Amount</th>
  </tr>
  <% @account.checks.each do |check| %>
  <tr>
  <td><%= check.date %></td>
  <td class = "name"><%= check.to %></td>
  <td><%= number_to_currency(check.amount) %></td>
  <td><%= link_to "delete", check, method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
  </tr>
  <% end %>
</table>

app/views/accounts/_deposits.html.erb
<table>

  <tr>
    <th>Date</th>
    <th>Received from</th>
    <th>Amount</th>
  </tr>
  <% @account.deposits.each do |deposit| %>
  <tr>
  <td><%= deposit.date %></td>
  <td class = "name"><%= deposit.from %></td>
  <td><%= number_to_currency(deposit.amount) %></td>
  <td><%= link_to "delete", deposit, method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
  </tr>
  <% end %>
</table>

app/views/accounts/index.html.erb
<ul>
<% @accounts.each do |account| %>
  <li><%= account.name %>, Balance: <%= number_to_currency(account.ending_balance) %> | <%= link_to "View", account_path(account) %></li>

<% end %>
</ul>
<%= link_to "create a new account", new_account_path, class: "button" %>

app/views/accounts/new.html.erb
<h1>Create a new account</h1>

<div>
<%= form_for(Account.new) do |f| %>


  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
  
<% end %>
</div>  

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1> 

<strong>Beginning balance: <%= number_to_currency(@account.balance) %></strong>

<h2>Checks</h2>

<%= render partial:  "checks" %>

<h2>Deposits</h2>

<%= render partial: "deposits" %>
  
<div>Total all checks: <%= number_to_currency(@account.total_expense) %></div>
<div>Total all deposits: <%= number_to_currency(@account.total_deposits) %></div>
<div><strong>Ending Balance: <%= number_to_currency(@account.ending_balance) %></strong></div>

<div><%= link_to "Delete", @account, method: :delete, data: { confirm: "Are you sure?" } %></div>

app/views/checks/_checks.html.erb
<table>

  <tr>
    <th>Date</th>
    <th>Paid to</th>
    <th>Amount</th>
  </tr>
  <% @checks.each do |check| %>
  <tr>
  <td><%= check.date %></td>
  <td class = "name"><%= check.to %></td>
  <td><%= number_to_currency(check.amount) %></td>
  <td><%= link_to "delete", check, method: :delete, data: {confirm: "Are you sure?"}, class: "button" %></td>
  </tr>
  <% end %>
</table>

app/views/checks/index.html.erb
<%= render partial:  "checks" %>

<%= link_to "Write a new check", new_check_path %>

app/views/checks/new.html.erb
<strong>Write a check</strong>
<div class="check">
<%= form_for(Check.new) do |f| %>


  <div class="date">
    <%= f.label :date %>:
    <%= f.text_field :date, size: 15 %>
  </div><br />


  <div class="payable_and_amount">
  <span class="payable_to">
    <%= f.label :to %>
    <%= f.text_field :to, size: 60 %>
  </span>

  <span class="amount">    
    <%= f.label :amount %>
    $<%= f.text_field :amount, size: 15 %>
  </span>
  </div>

  <div class="select_and_submit">  
    <span class="select"><%= select(:check, :account_id, @account_options) %></span>
    <span class="submit"><%= f.submit %></span>
  </div>  

<% end %>
</div>

app/views/checks/show.html.erb
<h1><%= @check_id %></h1>
<div><%= @check.date %>, <%= @check.to %>, Amount: <%= @check.amount %>, From: <%= @check.account.name %></div>
<div><%= link_to "Delete", @check, method: :delete, data: { confirm: "Are you sure?" } %></div>
<div><%= link_to "Back to list of checks", checks_path %></div>

app/views/deposits/new.html.erb
<strong>Enter a deposit</strong>
<div class = "deposit">
<%= form_for(Deposit.new) do |f| %>
    <div class="date">
    <%= f.label :date %>:
    <%= f.text_field :date, size: 15 %>
  </div><br />


  <div class="from_and_amount">
  <span class="from">
    <%= f.label :from %>
    <%= f.text_field :from, size: 60 %>
  </span>

  <span class="amount">    
    <%= f.label :amount %>
    $<%= f.text_field :amount, size: 15 %>
  </span>
  </div>

  <div class="select_and_submit">  
    <span class="select"><%= select(:deposit, :account_id, @account_options) %></span>
    <span class="submit"><%= f.submit %></span>
  </div>  

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckRegister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id = "navbar">
  <ul>
    <li><%= link_to "Accounts", accounts_path %></li>
    <li><%= link_to "Checks", checks_path %></li>
    <li><%= link_to "Write a check", new_check_path %></li>
    <li><%= link_to "Make a deposit", new_deposit_path %></li>
  </ul>
</div>


<%= yield %>

<% flash.each do |message_type, message| %>
  <div class = "alert alert-<%= message_type %>"><%= message %></div>
<% end %>

</body>
</html>